import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import '../models/transaction.dart';

class PdfGeneratorService {
  Future<List<int>> generateReport({
    required String period,
    required double income,
    required double expense,
    required double net,
    required List<TransactionModel> transactions,
    required String currencySymbol,
  }) async {
    final pdf = pw.Document();

    pdf.addPage(
      pw.Page(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(32),
        build: (pw.Context context) {
          return pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [
              // Header
              pw.Container(
                padding: const pw.EdgeInsets.only(bottom: 16),
                decoration: pw.BoxDecoration(
                  border: pw.Border(
                    bottom: pw.BorderSide(color: PdfColors.black, width: 2),
                  ),
                ),
                child: pw.Column(
                  crossAxisAlignment: pw.CrossAxisAlignment.start,
                  children: [
                    pw.Text(
                      'NEO.CASH',
                      style: pw.TextStyle(
                        fontSize: 32,
                        fontWeight: pw.FontWeight.bold,
                        color: PdfColors.yellow,
                      ),
                    ),
                    pw.SizedBox(height: 8),
                    pw.Text(
                      'FINANCIAL REPORT',
                      style: pw.TextStyle(
                        fontSize: 18,
                        fontWeight: pw.FontWeight.bold,
                        letterSpacing: 4,
                      ),
                    ),
                    pw.SizedBox(height: 4),
                    pw.Text(
                      period.toUpperCase(),
                      style: pw.TextStyle(
                        fontSize: 14,
                        color: PdfColors.grey700,
                      ),
                    ),
                  ],
                ),
              ),
              pw.SizedBox(height: 24),

              // Summary Section
              pw.Container(
                padding: const pw.EdgeInsets.all(16),
                decoration: pw.BoxDecoration(
                  color: PdfColors.grey100,
                  border: pw.Border.all(color: PdfColors.black, width: 2),
                ),
                child: pw.Row(
                  mainAxisAlignment: pw.MainAxisAlignment.spaceAround,
                  children: [
                    _buildSummaryItem('TOTAL INCOME', income, currencySymbol, PdfColors.green),
                    pw.SizedBox(width: 16),
                    _buildSummaryItem('TOTAL EXPENSE', expense, currencySymbol, PdfColors.pink),
                    pw.SizedBox(width: 16),
                    _buildSummaryItem('NET SAVINGS', net, currencySymbol,
                      net >= 0 ? PdfColors.yellow : PdfColors.red),
                  ],
                ),
              ),
              pw.SizedBox(height: 24),

              // Transactions Header
              pw.Text(
                'TRANSACTION DETAILS',
                style: pw.TextStyle(
                  fontSize: 16,
                  fontWeight: pw.FontWeight.bold,
                  letterSpacing: 2,
                ),
              ),
              pw.SizedBox(height: 16),

              // Transactions List
              ...transactions.map((transaction) {
                return _buildTransactionItem(transaction, currencySymbol);
              }),

              pw.SizedBox(height: 16),

              // Footer
              pw.Divider(color: PdfColors.black, thickness: 2),
              pw.SizedBox(height: 16),
              pw.Text(
                'Generated by Neo.Cash',
                style: pw.TextStyle(
                  fontSize: 10,
                  color: PdfColors.grey700,
                ),
              ),
            ],
          );
        },
      ),
    );

    return await pdf.save();
  }

  pw.Widget _buildSummaryItem(String label, double amount, String currency, PdfColor color) {
    return pw.Column(
      children: [
        pw.Text(
          label,
          style: pw.TextStyle(
            fontSize: 10,
            fontWeight: pw.FontWeight.bold,
            letterSpacing: 1,
          ),
        ),
        pw.SizedBox(height: 4),
        pw.Text(
          '$currency${amount.toStringAsFixed(0)}',
          style: pw.TextStyle(
            fontSize: 20,
            fontWeight: pw.FontWeight.bold,
            color: color,
          ),
        ),
      ],
    );
  }

  pw.Widget _buildTransactionItem(TransactionModel transaction, String currency) {
    final isIncome = transaction.type == 'income';
    final amountColor = isIncome ? PdfColors.green : PdfColors.pink;

    return pw.Container(
      margin: const pw.EdgeInsets.only(bottom: 8),
      padding: const pw.EdgeInsets.all(12),
      decoration: pw.BoxDecoration(
        border: pw.Border.all(color: PdfColors.black, width: 1),
      ),
      child: pw.Row(
        mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
        children: [
          pw.Expanded(
            child: pw.Column(
              crossAxisAlignment: pw.CrossAxisAlignment.start,
              children: [
                pw.Text(
                  transaction.title.isNotEmpty ? transaction.title : transaction.category,
                  style: pw.TextStyle(
                    fontSize: 12,
                    fontWeight: pw.FontWeight.bold,
                  ),
                ),
                pw.SizedBox(height: 4),
                pw.Row(
                  children: [
                    pw.Text(
                      '${transaction.category} • ',
                      style: pw.TextStyle(
                        fontSize: 10,
                        color: PdfColors.grey700,
                      ),
                    ),
                    pw.Text(
                      '${transaction.date.day}/${transaction.date.month}/${transaction.date.year}',
                      style: pw.TextStyle(
                        fontSize: 10,
                        color: PdfColors.grey700,
                      ),
                    ),
                  ],
                ),
                if (transaction.note != null && transaction.note!.isNotEmpty) ...[
                  pw.SizedBox(height: 4),
                  pw.Text(
                    transaction.note!,
                    style: pw.TextStyle(
                      fontSize: 9,
                      color: PdfColors.grey600,
                      fontStyle: pw.FontStyle.italic,
                    ),
                    maxLines: 1,
                  ),
                ],
              ],
            ),
          ),
          pw.Text(
            '${isIncome ? '+' : '-'}$currency${transaction.amount.toStringAsFixed(0)}',
            style: pw.TextStyle(
              fontSize: 14,
              fontWeight: pw.FontWeight.bold,
              color: amountColor,
            ),
          ),
        ],
      ),
    );
  }

  // Generate category breakdown chart page
  Future<List<int>> generateCategoryBreakdown({
    required Map<String, double> categoryTotals,
    required String currencySymbol,
  }) async {
    final pdf = pw.Document();

    pdf.addPage(
      pw.Page(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(32),
        build: (pw.Context context) {
          final total = categoryTotals.values.fold<double>(0, (sum, val) => sum + val);

          return pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [
              // Header
              pw.Container(
                padding: const pw.EdgeInsets.only(bottom: 16),
                decoration: pw.BoxDecoration(
                  border: pw.Border(
                    bottom: pw.BorderSide(color: PdfColors.black, width: 2),
                  ),
                ),
                child: pw.Column(
                  crossAxisAlignment: pw.CrossAxisAlignment.start,
                  children: [
                    pw.Text(
                      'NEO.CASH',
                      style: pw.TextStyle(
                        fontSize: 32,
                        fontWeight: pw.FontWeight.bold,
                        color: PdfColors.yellow,
                      ),
                    ),
                    pw.SizedBox(height: 8),
                    pw.Text(
                      'CATEGORY BREAKDOWN',
                      style: pw.TextStyle(
                        fontSize: 18,
                        fontWeight: pw.FontWeight.bold,
                        letterSpacing: 4,
                      ),
                    ),
                  ],
                ),
              ),
              pw.SizedBox(height: 24),

              // Category breakdown
              ...categoryTotals.entries.map((entry) {
                final percentage = total > 0 ? (entry.value / total) * 100 : 0;
                return pw.Container(
                  margin: const pw.EdgeInsets.only(bottom: 12),
                  child: pw.Column(
                    crossAxisAlignment: pw.CrossAxisAlignment.start,
                    children: [
                      pw.Row(
                        mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                        children: [
                          pw.Text(
                            entry.key,
                            style: pw.TextStyle(
                              fontSize: 12,
                              fontWeight: pw.FontWeight.bold,
                            ),
                          ),
                          pw.Text(
                            '$currencySymbol${entry.value.toStringAsFixed(0)} (${percentage.toStringAsFixed(1)}%)',
                            style: pw.TextStyle(
                              fontSize: 12,
                              fontWeight: pw.FontWeight.bold,
                            ),
                          ),
                        ],
                      ),
                      pw.SizedBox(height: 4),
                      pw.Container(
                        height: 8,
                        child: pw.LinearProgressIndicator(
                          value: percentage / 100,
                          backgroundColor: PdfColors.grey200,
                          valueColor: PdfColor.fromInt(0xFFFFD700), // Gold color
                        ),
                      ),
                    ],
                  ),
                );
              }),
            ],
          );
        },
      ),
    );

    return await pdf.save();
  }
}
